export interface StatState {

};

export interface StatAttackPowers {
  "NoneAttackPower": number,
  "DaggerAttackPower": number,
  "SwordAttackPower": number,
  "ShieldAttackPower":number,
  "GrimoireAttackPower":number,
  "CrossbowAttackPower": number,
  "Sword2hAttackPower": number,
  "StaffAttackPower": number,
  "BowAttackPower": number,
  "WandAttackPower": number,
  "SpearAttackPower": number,
};

export interface StatRow {
  "Point": number,
  "Type": string,
  "AttackPowers": StatAttackPowers,
  "BonusAttackPowers": StatAttackPowers,
  "AttackSpeedModifier": number,
  "AttackSpeedMainHand": number,
  "MeleeAccuracy": number,
  "RangeAccuracy": number,
  "MagicAccuracy": number,
  "MeleeEvasion": number,
  "RangeEvasion": number,
  "MagicEvasion": number,
  "HpMax": number,
  "HpRegen": number,
  "CostMax": number,
  "CostRegen": number,
  "WeakenAccuracy": number,
  "StunAccuracy": number,
  "PetrificationAccuracy": number,
  "SleepAccuracy": number,
  "SilenceAccuracy": number,
  "BindAccuracy": number,
  "BlindAccuracy": number,
  "CollideAmplification": number,
  "MeleeCriticalAttack": number,
  "RangeCriticalAttack": number,
  "MagicCriticalAttack": number,
  "MeleeArmor": number,
  "RangeArmor": number,
  "MagicArmor": number,
  "SkillCooldownModifier": number,
  "BuffGivenDurationModifier": number,
  "MeleeCriticalDefense": number,
  "RangeCriticalDefense": number,
  "MagicCriticalDefense": number,
  "MeleeDoubleDefense": number,
  "RangeDoubleDefense": number,
  "MagicDoubleDefense": number,
  "SkillPowerResistance": number,
  "WeakenTolerance": number,
  "StunTolerance": number,
  "PetrificationTolerance": number,
  "SleepTolerance": number,
  "SilenceTolerance": number,
  "BindTolerance": number,
  "BlindTolerance": number,
  "CollideResistance": number,
};
